// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmlRZUu6EyHo8hLYFrg2Sn6EW5xn1wEoE',
    appId: '1:459284716238:android:efb9be07cdf1406db80e9f',
    messagingSenderId: '459284716238',
    projectId: 'chat-45e15',
    storageBucket: 'chat-45e15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0vd49_I0IUIcB2qm1aaRCdMqwih8QYRg',
    appId: '1:459284716238:ios:2d1e2cb0165add2fb80e9f',
    messagingSenderId: '459284716238',
    projectId: 'chat-45e15',
    storageBucket: 'chat-45e15.firebasestorage.app',
    androidClientId: '459284716238-s35q897ijjfunokv0f0jd8hsih9ur01n.apps.googleusercontent.com',
    iosClientId: '459284716238-45oapclk0khjf25o0m3bihjc8v3kmu77.apps.googleusercontent.com',
    iosBundleId: 'com.jjhwnn.chat',
  );
}
