// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWWivbXWkOF1YivrnYiMX2dPeeB4yyG8E',
    appId: '1:459284716238:web:04595dbd8356b370b80e9f',
    messagingSenderId: '459284716238',
    projectId: 'chat-45e15',
    authDomain: 'chat-45e15.firebaseapp.com',
    storageBucket: 'chat-45e15.firebasestorage.app',
    measurementId: 'G-PG06884CNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmlRZUu6EyHo8hLYFrg2Sn6EW5xn1wEoE',
    appId: '1:459284716238:android:94867215059faa7cb80e9f',
    messagingSenderId: '459284716238',
    projectId: 'chat-45e15',
    storageBucket: 'chat-45e15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0vd49_I0IUIcB2qm1aaRCdMqwih8QYRg',
    appId: '1:459284716238:ios:5650de9cd1ef1ef1b80e9f',
    messagingSenderId: '459284716238',
    projectId: 'chat-45e15',
    storageBucket: 'chat-45e15.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0vd49_I0IUIcB2qm1aaRCdMqwih8QYRg',
    appId: '1:459284716238:ios:5650de9cd1ef1ef1b80e9f',
    messagingSenderId: '459284716238',
    projectId: 'chat-45e15',
    storageBucket: 'chat-45e15.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWWivbXWkOF1YivrnYiMX2dPeeB4yyG8E',
    appId: '1:459284716238:web:b37316a94af6717cb80e9f',
    messagingSenderId: '459284716238',
    projectId: 'chat-45e15',
    authDomain: 'chat-45e15.firebaseapp.com',
    storageBucket: 'chat-45e15.firebasestorage.app',
    measurementId: 'G-79XTCVVE72',
  );
}
